### ISSUE TITLE
Provide a user selectable output stage

### ISSUE THREAD

**Issue by aireilly** [aidanreilly/sines#21]
Users should be able to select the output stage

1 tanh distortion 
2 limiting 
3 softclip 
4 no clipping protection 
5 ???

**Comment by aireilly** [comment]
untested. basic idea:

```supercollider
SynthDef(\my_synth, {
    arg out=0, pan=0, freq=440, amp=0.5, distortion=0;

    var sig, clip_sig;

    sig = SinOsc.ar(freq);

    if(distortion == 1, {
        clip_sig = Tanh.ar(sig);
    }, {
        clip_sig = sig;
    });

    sig = clip_sig * amp * 2 ** 0.5;
    sig = Pan2.ar(sig, pan);

    Out.ar(out, sig);
}).add;

s.boot;

// play a note with clipping protection
Synth(\my_synth, [\distortion, 1]);

// play a note without clipping protection
Synth(\my_synth, [\distortion, 0]);

```

**Comment by p3r7** [comment]
nice.

also, if wanting to support more than 2 modes, there is the [switch](https://depts.washington.edu/dxscdoc/Help/Reference/Control-Structures.html#switch) language construct.

i guess the change would be constricted in `\sines_output` SynthDef introduced by https://github.com/aidanreilly/sines/pull/20.

**Comment by aireilly** [comment]
Also: 
https://llllllll.co/t/supercollider-tips-q-a/3185/509

**Comment by aireilly** [comment]
Also also: 
https://llllllll.co/t/sines/39292/359

**Comment by aidanreilly** [comment]
Closing this because on reflection this adds a level of feature creep that IMO just isn't needed.
