### ISSUE TITLE
Changing scale also changes the octave of selected pitches

### ISSUE THREAD

**Issue by lazzarello** [aidanreilly/sines#8]
Leaving this here as a note. I'm practicing for a live performance and changed the scale in the parameters and all the notes I had previously selected were reset to the octave from the defaults, which was quite a surprise for the bass voice I had going :)

I'll take a look when I get up to date with the master branch + my arc branch.

**Comment by aidanreilly** [comment]
just seeing this! this will absolutely happen, and is by default - changing scales will reset octaves. all notes are reset when you change scale.
